### PR TITLE
Improve various language stuff

### PR DESCRIPTION
**Pull request by mt-clearhaus**
No regenerated PDF yet.

### CODE REVIEW

**Review by noxern — DISMISSED** [review]
:cake:

**Comment by ianmurrays** [comment]
I believe "extreme weather" should be clarified.

**Review by kse-clearhaus — APPROVED** [review]

**Comment by kse-clearhaus** [comment]
I'm missing a :pr: emoji @ianmurrays.

**Comment by mt-clearhaus** [comment]
> I believe "extreme weather" should be clarified.

Well, me too, however, let's say it's out of scope for this PR :stuck_out_tongue_closed_eyes:

**Comment by tma-clearhaus** [comment]
If 2018 taught us anything it is that all that matters is how you feel. In other words. If Kasper thinks it is too windy to bike to work then that is extreme to him and he should get cake. Anyone who denies a victim his or her cake is an oppressor.

**Comment by madsmadsen** [comment]
> If 2018 taught us anything it is that all that matters is how you feel. In other words. If Kasper thinks it is too windy to bike to work then that is extreme to him and he should get cake. Anyone who denies a victim his or her cake is an oppressor.

So basically, if you complain about the weather, get cake?

**Pull request merged**
